version: '3.7'
services:
  dawnpool-oracle:
    build: .
#    image: registry.cn-hongkong.aliyuncs.com/test-okpool/dawnpool-oracle:latest
    platform: linux/amd64  # m1芯片构建不成功
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: host
    environment:
#      WEB3_PROVIDER_URI: https://goerli.infura.io/v3/5fc8deacd5e24454b4d57188808dfcc1
      WEB3_PROVIDER_URI: http://47.75.111.121:18545
      BEACON_NODE: http://47.75.111.121:18052
      REWARDS_VAULT_ADDRESS: "0x09B9a97770093513b81AC53D9A815f3eA86D4511"
#      POOL_CONTRACT: "0x75C19B313F4b940716443Cb4BA27e50899F5bbCf"
#      ORACLE_CONTRACT: "0x49eeA6937Ffc7E530761A17C3E494f3DB33eDCcE"
#      NODE_MANAGER_CONTRACT: "0xd0770d677d0369BE7cE861C837a0CA4253b366c3"
      POOL_CONTRACT: "0x9a8E4ae2fAd1f196a80d28bE375D0147FD8e4846"
      ORACLE_CONTRACT: "0x47ed8d4bCE7e180116Ee263c8CAC0C103172F5d8"
      NODE_MANAGER_CONTRACT: "0x1E4f4fd4513dCE5FdD51e7e00c9ea0Ca093986cD"
      BURNER_CONTRACT: "0x1E4f4fd4513dCE5FdD51e7e00c9ea0Ca093986cD"
      MEMBER_PRIV_KEY: "e0c5a21495e5e0134db55fef98eeb7030b1e72f027e0724df8a2feb385725f22"
      ORACLE_FROM_BLOCK: 9060000
      DAEMON: 1
      CONSIDER_WITHDRAWALS_FROM_EPOCH: 191900


#EL：http://47.75.111.121:18545
#CL：http://47.75.111.121:18052


#DawnStorage：0xf0718B4182C67Bbb94c0eDe3850cD41a4c44Ab6d
#DawnDeposit：0x9a8E4ae2fAd1f196a80d28bE375D0147FD8e4846
#RewardsVault：0x87167FD3e2C2897B9aA66957CfD79A420b543e71
#DawnInsurance：0x32a3fD7024B4ed67De1d331091f0075DF0243bDd
#DawnTreasury： 0xe00c3897596983A9457B0a5D36059A6Cc210d2BC
#DepositNodeManager: 0x1E4f4fd4513dCE5FdD51e7e00c9ea0Ca093986cD
#DepositNodeOperatorDeployer: 0x812F50E63eB2848d2273D15A670f2F322cBa53F9
#DawnPoolOracle:  0x47ed8d4bCE7e180116Ee263c8CAC0C103172F5d8